import mongoose from "mongoose";

const FeedbackSchema = new mongoose.Schema(
  {
    interviewId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Interview",
      required: true,
    },
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    overallRating: {
      type: Number,
      min: 1,
      max: 5,
      required: true,
    },
    strengths: {
      type: [String],
      default: [],
    },
    improvements: {
      type: [String],
      default: [],
    },
    aiSummary: {
      type: String,
    },
    aiGenerated: {
      type: Boolean,
      default: false, // Useful if feedback was generated by AI
    },
  },
  { timestamps: true }
);

export default mongoose.model("Feedback", FeedbackSchema);
